export const projects = [
  {
    title: "Vakay",
    subtitle: "Next.js, Firebase, Auth0",
    description: "",
    image: "",
    link: "",
  },
  {
    title: "ifGift",
    subtitle: "React, Koa, MongoDB",
    description: "",
    image: "",
    link: "",
  },
  {
    title: "Subscriber",
    subtitle: "React, Typescript",
    description: "",
    image: "",
    link: "",
  },
  {
    title: "UCSD, Cognitive Tools Lab",
    subtitle: "HTML, CSS, Javascript",
    description: "",
    image: "",
    link: "",
  },
  {
    title: "Doctor Banjo",
    subtitle: "React, Netlify",
    description: "",
    image: "",
    link: "",
  }
];

export const skills = [
  "HTML",
  "CSS",
  "Javascript",
  "Typescript",
  "WCAG",
  "React",
  "React Hooks",
  "Next.js",
  "Material UI",
  "Firebase",
  "Auth0",
  "NodeJS",
  "JSON",
  "Express",
  "Koa",
  "MongoDB",
  "Mongoose",
  "MySQL",
  "PostgresQL",
  "Postman",
  "Figma",
  "UIzard",
  "Asana",
  "Jira",
  "Slack",
  "Discord"
]